FROM quay.io/signalfuse/collectd:latest

# Disable everything we can except elasticsearch
ENV COLLECTD_INTERVAL=3 COLLECTD_HOSTNAME=couchbase-test DISABLE_AGGREGATION=true DISABLE_CPU=true DISABLE_CPUFREQ=true DISABLE_DF=true DISABLE_DISK=true DISABLE_DOCKER=true DISABLE_HOST_MONITORING=true DISABLE_INTERFACE=true DISABLE_LOAD=true DISABLE_MEMORY=true DISABLE_PROTOCOLS=true DISABLE_VMEM=true DISABLE_UPTIME=true

# Debian is super minimalistic
RUN apt-get update &&\
    apt-get install -yq netcat curl

CMD /.docker/setup_couchbase
ADD integration-test/setup_couchbase /.docker/setup_couchbase

## The context of the image build should be the root dir of this repo!!
ADD couchbase.py metric_info.py /opt/collectd-couchbase/
ADD integration-test/20-couchbase-test.conf /etc/collectd/managed_config/
